lecture10 commit
sho1122/RaiseTech pull request #12
Opened 2023-08-10 15:42 UTC by sho1122

第１０回の課題を提出します。

2023-08-10 16:26 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！
https://github.com/sho1122/RaiseTech/pull/12/files

2023-08-10 16:26 UTC, MasatoshiMizumoto commented on lecture10/.DS_Store
このファイルは不要なのでGitに含まないように恒久対策お願いします！！

2023-08-10 16:26 UTC, MasatoshiMizumoto commented on lecture10/lecture10.xlsx
このファイルは何があるんでしょうかね？
あんまりGit管理するのは望ましくないのですが、意味があるなら説明書きをGit対応ファイルのどこかにしておいてください。

2023-08-10 16:26 UTC, MasatoshiMizumoto commented on lecture10/lecture10.md
画像全般ですが、これは日本語名にしているのでしょうか？
英数の命名規則にしてもらったほうが視認性が良いかなと思います！

2023-08-10 22:52 UTC, sho1122 commented on lecture10/lecture10.xlsx
修正しました。

2023-08-10 22:52 UTC, sho1122 commented on lecture10/lecture10.md
英語名に修正しました。

2023-08-10 22:53 UTC, sho1122 commented on lecture10/.DS_Store
修正しました。

2023-08-11 02:02 UTC, MasatoshiMizumoto commented on lecture10/.DS_Store
もう入らないように恒久対策ってできてますかね？
消しただけではまた入ってしまうので！

2023-08-12 03:06 UTC, sho1122 commented on lecture10/.DS_Store
削除しただけになっていたので、下のサイトを参考に恒久対策をしました。
https://tips-memo.com/git-dsstore

2023-08-12 03:30 UTC, MasatoshiMizumoto approved these changes
LGTM!

2023-08-16 02:08 UTC, merged